=== Dem0nGrFt/Programacion/Lenguaje_de_Marcas/XSD/xsd13.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="library">
        <xs:complexType>
            <xs:sequence>
                <!-- Definición de libros -->
                <xs:element name="book" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="isbn" type="xs:NMTOKEN" />
                            <xs:element name="title" type="xs:string" />
                            <xs:element name="author-ref">
                                <!-- Referencias a otros autores -->
                                <xs:complexType>
                                    <xs:attribute name="ref" type="xs:IDREF" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <!-- Identificador único del libro -->
                        <xs:attribute name="identifier" type="xs:ID" use="required" />
                    </xs:complexType>
                </xs:element>

                <!-- Definición de autores -->
                <xs:element name="author" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <!-- Identificador único del autor -->
                                <xs:attribute name="id" type="xs:ID" use="required" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Dem0nGrFt/Programacion/Lenguaje_de_Marcas/XSD/Prueba13.xml
<?xml version="1.0" encoding="UTF-8"?>
<library xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
         xs:noNamespaceSchemaLocation="xsd13.xsd">

    <!-- Definición de libros -->
    <book identifier="book1">
        <isbn>978-3-16-148410-0</isbn>
        <title>The Great Gatsby</title>
        <author-ref ref="author1" />
    </book>
    <book identifier="book2">
        <isbn>978-0-14-118263-6</isbn>
        <title>1984</title>
        <author-ref ref="author2" />
    </book>
    <book identifier="book3">
        <isbn>978-1-56619-909-4</isbn>
        <title>To Kill a Mockingbird</title>
        <author-ref ref="author3" />
    </book>
    <book identifier="book4">
        <isbn>978-0-452-28423-4</isbn>
        <title>Brave New World</title>
        <author-ref ref="author4" />
    </book>
    
        <!-- Definición de autores -->
        <author id="author1">F. Scott Fitzgerald</author>
        <author id="author2">George Orwell</author>
        <author id="author3">Harper Lee</author>
        <author id="author4">Aldous Huxley</author>
    
</library>
