=== Dem0nGrFt/Programacion/Lenguaje_de_Marcas/XSD/xsd11.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="productosfinancieros">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="producto" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
</xs:element>
<xs:element name="producto">
    <xs:complexType>
        <xs:choice>
            <xs:element ref="bono" />
            <xs:element ref="acciones" />
        </xs:choice>
    </xs:complexType>
</xs:element>
<xs:element name="bono">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="valoractual" />
            <xs:element name="beneficio" type="xs:decimal" />
        </xs:sequence>
    </xs:complexType>
</xs:element>
<xs:element name="valoractual">
    <xs:complexType>
        <xs:simpleContent>
            <xs:extension base="xs:decimal">
                <xs:attribute name="moneda" type="tipomoneda" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:element>
<xs:simpleType name="tipomoneda">
    <xs:restriction base="xs:string">
        <xs:enumeration value="dolares" />  <xs:enumeration value="euros" />
 <xs:enumeration
            value="yenes" />
    </xs:restriction>
</xs:simpleType>
<xs:element name="acciones">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="empresa" />
            <xs:element name="beneficio" type="xs:decimal" />
        </xs:sequence>
    </xs:complexType>
</xs:element>
<xs:element name="empresa">
    <xs:complexType>
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="pais" type="xs:string" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:element>
</xs:schema>

=== Dem0nGrFt/Programacion/Lenguaje_de_Marcas/XSD/Prueba11.xml
<?xml version="1.0" encoding="UTF-8"?>
<productosfinancieros xmlns:xsi="http://www.w3.org/2001/XMLSchemainstance"
    xsi:noNamespaceSchemaLocation="xsd11.xsd">
    <producto>
        <bono>
            <valoractual moneda="yenes">2.212</valoractual>
            <beneficio>-2.83</beneficio>
        </bono>
    </producto>
    <producto>
        <acciones>
            <empresa pais="usa">ENRON</empresa>
            <beneficio>2.91</beneficio>
        </acciones>
    </producto>
    <producto>
        <bono>
            <valoractual moneda="euros">1.3</valoractual>
            <beneficio>+3.5</beneficio>
        </bono>
    </producto>
</productosfinancieros>
