=== Dem0nGrFt/Programacion/Lenguaje_de_Marcas/XSD/xsd7.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="alumnos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="alumno" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="edad" type="xs:int"/>
              <xs:element name="direccion" maxOccurs="2">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="calle" type="xs:string"/>
                    <xs:element name="ciudad" type="xs:string" minOccurs="1"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="telefono" maxOccurs="3">
                <xs:simpleType>
                  <xs:restriction base="xs:string"/>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="ies" type="xs:string"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Dem0nGrFt/Programacion/Lenguaje_de_Marcas/XSD/Prueba7.xml
<?xml version="1.0" encoding="UTF-8"?>
<alumnos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd7.xsd">
  <alumno ies="IES Ejemplo">
    <nombre>Juan Pérez</nombre>
    <edad>18</edad>
    <direccion>
      <calle>Calle Ficticia 123</calle>
      <ciudad>Madrid</ciudad>
    </direccion>
    <direccion>
      <calle>Avenida Central 456</calle>
      <ciudad>Barcelona</ciudad>
    </direccion>
    <telefono>612345678</telefono>
    <telefono>612345679</telefono>
  </alumno>

  <alumno ies="IES Innovación">
    <nombre>Ana López</nombre>
    <edad>19</edad>
    <direccion>
      <calle>Calle Real 789</calle>
      <ciudad>Sevilla</ciudad>
    </direccion>
    <telefono>612987654</telefono>
  </alumno>

</alumnos>
