=== Dem0nGrFt/Programacion/Lenguaje_de_Marcas/XSD/xsd8.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Definir a estrutura para o medio de transporte con choice -->
    <xs:complexType name="TransportType">
        <xs:sequence>
            <xs:choice>
                <xs:element name="moto" type="xs:string" />
                <xs:element name="coche" type="xs:string" />
                <xs:element name="tren" type="xs:string" />
                <xs:element name="avion" type="xs:string" />
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

    <!-- Definir a estrutura para un viaxe -->
    <xs:complexType name="ViaxeType">
        <xs:sequence>
            <xs:element name="data" type="xs:date" />
            <xs:element name="kilometros" type="xs:int" />
            <xs:element name="medioTransporte" type="TransportType" />
        </xs:sequence>
    </xs:complexType>

    <!-- Definir o elemento raíz que contén as viaxes -->
    <xs:element name="viaxes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="viaxe" maxOccurs="unbounded" type="ViaxeType" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Dem0nGrFt/Programacion/Lenguaje_de_Marcas/XSD/Prueba8.xml
<?xml version="1.0" encoding="UTF-8"?>
<viaxes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="xsd8.xsd">

    <viaxe>
        <data>2024-11-10</data>
        <kilometros>150</kilometros>
        <medioTransporte>
            <moto />
        </medioTransporte>
    </viaxe>

    <viaxe>
        <data>2024-11-15</data>
        <kilometros>200</kilometros>
        <medioTransporte>
            <coche />
        </medioTransporte>
    </viaxe>

    <viaxe>
        <data>2024-11-18</data>
        <kilometros>1200</kilometros>
        <medioTransporte>
            <tren />
        </medioTransporte>
    </viaxe>

    <viaxe>
        <data>2024-11-20</data>
        <kilometros>3000</kilometros>
        <medioTransporte>
            <avion />
        </medioTransporte>
    </viaxe>

</viaxes>
