=== Dem0nGrFt/Programacion/Lenguaje_de_Marcas/DTD/dtd4.dtd
<!ELEMENT pedidos (pedido*)>
<!ELEMENT pedido (codigo, cantidad, peso?)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT peso (#PCDATA)>

=== Dem0nGrFt/Programacion/Lenguaje_de_Marcas/DTD/Prueba4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pedidos SYSTEM "dtd4.dtd">
<pedidos>
    <pedido>
        <codigo>01</codigo>
        <cantidad>10</cantidad>
        <peso>5g</peso>
    </pedido>
    <pedido>
        <codigo>02</codigo>
        <cantidad>9</cantidad>
    </pedido>
    <pedido>
        <codigo>03</codigo>
        <cantidad>2</cantidad>
        <peso>33.47Kg</peso>
    </pedido>
</pedidos>
