=== Dem0nGrFt/Programacion/Lenguaje_de_Marcas/DTD/dtd7.dtd
<!ELEMENT lista_de_personas (persona+)>
<!ELEMENT persona (nombre, fecnac, telefono+, sexo?, numss?)>
<!ATTLIST persona nacionalidad CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fecnac (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT sexo (#PCDATA)>
<!ELEMENT numss (#PCDATA)>

=== Dem0nGrFt/Programacion/Lenguaje_de_Marcas/DTD/Prueba7.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lista_de_personas SYSTEM "dtd7.dtd">
<lista_de_personas>
  <persona nacionalidad="español">
    <nombre>José García</nombre>
    <fecnac>25/04/1984</fecnac>
    <telefono>670201256</telefono>
    <telefono>968472898</telefono>
    <sexo>Varón</sexo>
  </persona>
  <persona nacionalidad="español">
    <nombre>Juan Antonio</nombre>
    <fecnac>25/04/1984</fecnac>
    <telefono>670201256</telefono>
    <numss>2569587412569</numss>
  </persona>
</lista_de_personas>
