=== Dem0nGrFt/Programacion/Lenguaje_de_Marcas/DTD/dtdcient.dtd
<!ELEMENT rede (cientifico+)>
<!ELEMENT cientifico (nome, colaboradores)>
<!ATTLIST cientifico ide ID #REQUIRED>

<!ELEMENT nome (#PCDATA)>
<!ELEMENT colaboradores (colaborador+)>
<!ELEMENT colaborador EMPTY>
<!ATTLIST colaborador idref IDREF #REQUIRED>

=== Dem0nGrFt/Programacion/Lenguaje_de_Marcas/DTD/Pruebacient.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rede SYSTEM "dtdcient.dtd">
<rede>
  <cientifico ide="C1">
    <nome>Maria Sánchez</nome>
    <colaboradores>
      <colaborador idref="C2"/>
      <colaborador idref="C3"/>
    </colaboradores>
  </cientifico>

  <cientifico ide="C2">
    <nome>Juan López</nome>
    <colaboradores>
      <colaborador idref="C1"/>
      <colaborador idref="C3"/>
    </colaboradores>
  </cientifico>

  <cientifico ide="C3">
    <nome>Ana Fernández</nome>
    <colaboradores>
      <colaborador idref="C1"/>
      <colaborador idref="C2"/>
    </colaboradores>
  </cientifico>
</rede>
