=== Dem0nGrFt/Programacion/Lenguaje_de_Marcas/DTD/dtdz.dtd
<!ELEMENT cd (canciones | data)>
<!ATTLIST cd titulo CDATA #REQUIRED>

<!ELEMENT canciones (cancion+)>

<!ELEMENT cancion (titulo, compositores, productores, sello, artista)>
<!ATTLIST cancion duracion CDATA #REQUIRED>
<!ATTLIST cancion anio CDATA #REQUIRED>

<!ELEMENT titulo (#PCDATA)>

<!ELEMENT compositores (compositor+)>
<!ELEMENT compositor (nombres, apellidos)>
<!ELEMENT nombres (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>

<!ELEMENT productores (productor+)>
<!ELEMENT productor (nombres, apellidos)>

<!ELEMENT sello (#PCDATA)>
<!ELEMENT artista (#PCDATA)>

<!ELEMENT data EMPTY>
<!ATTLIST data dia CDATA #REQUIRED>
<!ATTLIST data mes CDATA #REQUIRED>
<!ATTLIST data anio CDATA #REQUIRED>

=== Dem0nGrFt/Programacion/Lenguaje_de_Marcas/DTD/Pruebaz.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cd SYSTEM "dtdz.dtd">
<cd titulo="Greatest Hits">
    <canciones>
      <cancion duracion="4:47" anio="2008">
        <titulo>Give it 2 me</titulo>
        <compositores>
          <compositor>
            <nombres>Pharrell</nombres>
            <apellidos>Williams</apellidos>
          </compositor>
        </compositores>
        <productores>
          <productor>
            <nombres>Pharrell</nombres>
            <apellidos>Williams</apellidos>
          </productor>
        </productores>
        <sello>Warner Bros. Records</sello>
        <artista>Madonna</artista>
      </cancion>
      <!-- Máis cancións poden ir aquí -->
    </canciones>
  </cd>
